
name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: Statiq.Docs
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Get Source
        uses: actions/checkout@v2
        with:
          path: Statiq.Docs

      - name: Checkout Statiq.Framework
        uses: actions/checkout@v2
        with:
          repository: statiqdev/Statiq.Framework
          path: Statiq.Framework

      - name: Checkout Statiq.Web
        uses: actions/checkout@v2
        with:
          repository: statiqdev/Statiq.Web
          path: Statiq.Web

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Build and Test
        run: dotnet run --project "build/Statiq.Docs.Build/Statiq.Docs.Build.csproj" -- test
        env:
          StatiqFrameworkVersion: local
          StatiqWebVersion: local